language: php

dist: bionic

php:
  - 7.3

matrix:
  fast_finish: true

before_install:
  - composer clear-cache

install:
  - composer install -d ./src --ignore-platform-reqs

before_script:
  - echo 'zend.assertions=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'assert.exception=On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - cd ./src
  - ./vendor/bin/phpunit

notifications:
  email: false