version: "3"
services:
  mongodb:
    image: mongo:latest
    volumes:
     - ~/.mongodb/data/db:/data/db
    ports:
      - "27017:27017"
  php-fpm:
    build: ./php-fpm
    volumes:
      - ../:/var/www/html
    links:
      - mongodb
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html
    links:
      - php-fpm
